twig:
    file_name_pattern: '*.twig'

<<<<<<< HEAD
=======
    form_themes:
        - 'bootstrap_5_layout.html.twig'

>>>>>>> 7725b0c3ef619896f07c7ee44ee1ac2e401a68f0
when@test:
    twig:
        strict_variables: true
